version: '3.8'

services:
  slang-translator:
    build: .
    container_name: slang-translator-app
    ports:
      - "5000:5000"
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      - FLASK_APP=web_app/app.py
      - FLASK_ENV=production
    volumes:
      - ./logs:/app/logs
      - model_cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  model_cache:
