apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: slang-translator
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/slang-translator:latest
        ports:
        - containerPort: 8080
        env:
        - name: HUGGINGFACE_HUB_TOKEN
          value: "f_dHMvtQsUlDqCIBaWCSJfpgcsVwnVArbdQw"
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
